#include <cs50.h>
// Answers to Wheel of Fortune from Nov 15th 2012, found on
// https://www.playstationtrophies.org/forum/topic/163466-wheel-of-fortune-answer-list/ Most likely the answers on the Wheel of
// Fortune Playstation game, based on what the website is all about.
string phrases[] = {"address book",
                    "after-shave lotion",
                    "bookshelf",
                    "bean bag chair",
                    "bookends",
                    "ceramic bowl",
                    "citrus-scented shower gel",
                    "electric toothbrush",
                    "fishing tackle box",
                    "home office",
                    "jewel box",
                    "lava lamp",
                    "linen napkins",
                    "mousepad",
                    "oak china cabinet",
                    "polishing wax",
                    "pens and pencils",
                    "photo album",
                    "proficiently displayed awards",
                    "pruning shears",
                    "reclining lounge chair",
                    "shampoo & conditioner",
                    "sturdy table",
                    "window screens",
                    "wooden table",
                    "babbitt",
                    "cat's cradle",
                    "jane eyre",
                    "the big sleep",
                    "the scarlet letter",
                    "the house of mirth",
                    "the south beach diet",
                    "an american in paris",
                    "casablanca",
                    "south pacific",
                    "the blob",
                    "the dirty dozen",
                    "alice, flo, vern, & mel",
                    "bonanza",
                    "bull the bailiff",
                    "don johnson stars in miami vice",
                    "f troop",
                    "howard & marion cunningham",
                    "hawaii five-o",
                    "marcia! marcia! marcia!",
                    "miami vice",
                    "a side trip to oxford university",
                    "a cruise to the island",
                    "act of congress",
                    "bonfire",
                    "big bash",
                    "caribbean vacation",
                    "catamaran sailing cruise",
                    "cinco de mayo",
                    "catered party",
                    "dazzling sunset",
                    "family reunion",
                    "fishing tournament",
                    "formal dinner",
                    "harbor cruise",
                    "high school reunion",
                    "holiday parade",
                    "independence day",
                    "international flight",
                    "leap year",
                    "los angeles marathon",
                    "marriage ceremony",
                    "memorial day",
                    "opening night",
                    "open house",
                    "pivotal moment",
                    "presidential debate",
                    "private tour",
                    "reef diving",
                    "running a marathon",
                    "saltwater fishing trip",
                    "school christmas pageant",
                    "spring white sale",
                    "sunny afternoon",
                    "touring the windy city",
                    "travel expo",
                    "unforgettable vacation",
                    "a cruise through glacier bay",
                    "all-expenses paid vacation",
                    "annual meeting",
                    "annual sale",
                    "boardroom meeting",
                    "business convention",
                    "camping road trip",
                    "caribbean getaway",
                    "comic book convention",
                    "daring parachute jump",
                    "dog days of summer",
                    "grand tour",
                    "harbor cruise",
                    "holiday weekend",
                    "humid weather",
                    "ideal vacation",
                    "independence day",
                    "invigorating walk",
                    "job fair",
                    "ocean-view dining",
                    "private tour",
                    "sailboat race",
                    "sandstorm",
                    "sightseeing cruise",
                    "spelling bee",
                    "shows with spectacular stunts",
                    "sunny warm weekend",
                    "state dinner",
                    "summer vacation",
                    "waterfront dining",
                    "wild-goose chase",
                    "godfather & godmother",
                    "paris and nicky hilton",
                    "will & willow smith",
                    "eeyore & tigger",
                    "ebenezer scrooge",
                    "fred flintstone",
                    "hercules",
                    "homer simpson",
                    "jacob marley",
                    "nick fury",
                    "old king cole",
                    "santa's elves",
                    "the incredible hulk",
                    "the green lantern",
                    "top cat",
                    "tweedledum",
                    "the cat in the hat",
                    "vegas vic",
                    "american cheddar cheese",
                    "baked fruit compote",
                    "bean dip",
                    "bagels and lox",
                    "beans & cornbread",
                    "bottled water",
                    "buffalo burger",
                    "butterhead lettuce",
                    "basil leaves",
                    "chicken quesadillas",
                    "celery root salad",
                    "chocolate syrup",
                    "cool treats",
                    "cheese pizza",
                    "chocolate toffee",
                    "creamy ricotta cheese",
                    "chicken salad",
                    "chocolate mousse",
                    "deep-dish pizza",
                    "delicious cuisine",
                    "deli sandwich",
                    "deep-dish peach pie",
                    "ear of corn",
                    "empanadas",
                    "english toffee",
                    "fresh fruit platter",
                    "fresh parsnips",
                    "fresh pineapple juice",
                    "fried seafood platter",
                    "fruit cocktail",
                    "french fries",
                    "gala apples",
                    "green turtle soup",
                    "green corn tamales",
                    "grandma's fruitcake",
                    "homemade pasta",
                    "habanero sauce",
                    "hawaiian feast",
                    "huevos rancheros",
                    "juicy pineapple",
                    "kosher salt",
                    "key lime pie",
                    "lemon-garlic chicken",
                    "lemon drops",
                    "lemon poppy seed muffins",
                    "liver dumplings",
                    "milk chocolate bar",
                    "mincemeat pie",
                    "nachos supreme",
                    "okra salad",
                    "organic brazil nuts",
                    "oven-fried chicken",
                    "oysters on the half shell",
                    "pasta with parmesan cheese",
                    "peach tea",
                    "pan gravy",
                    "poached pared fruit",
                    "peppermint candy cane",
                    "red velvet cake",
                    "ripe bananas",
                    "rhubarb pie",
                    "salad vegetables",
                    "sausage and potatoes",
                    "seared pork",
                    "shepherd's pie",
                    "seafood tetrazzini",
                    "skinned tangelo",
                    "smoked ham",
                    "smoked trout",
                    "spicy cocktail sauce",
                    "seedless watermelon",
                    "thin-crust pizza",
                    "tea and crumpets",
                    "thompson seedless grapes",
                    "tuna salad sandwich",
                    "vegetable juice",
                    "vegetable soup",
                    "wedding cake",
                    "yellow bell peppers",
                    "arm wrestling",
                    "afterschool activities",
                    "a dip in the pool",
                    "balloon animals",
                    "belly dancing",
                    "catching a wave",
                    "cross-country skiing",
                    "jousting",
                    "kayak polo",
                    "knight bishop & pawn",
                    "movie studio tour",
                    "modeling clay",
                    "ocean kayak",
                    "poker chips",
                    "playing ice hockey",
                    "playing stickball",
                    "racquetball",
                    "rock climbing",
                    "slot machine",
                    "thumb wrestling",
                    "trolley tour",
                    "video poker",
                    "aluminum cheese grater",
                    "glass bowl",
                    "baking dish",
                    "canned goods",
                    "conical strainer",
                    "conventional oven",
                    "drinking straws",
                    "gravy ladle",
                    "insulated teapot",
                    "lemon and lime squeezer",
                    "stand mixer",
                    "arlington house",
                    "bunker hill monument",
                    "capitol hill",
                    "circus circus",
                    "denali national park",
                    "fremont street",
                    "great sand dunes national park",
                    "hoover dam",
                    "judiciary square",
                    "liberace museum",
                    "luxor's pyramid",
                    "madison square garden",
                    "memorial bridge",
                    "muscle beach",
                    "national arboretum",
                    "national gallery of art",
                    "national mall",
                    "penn station",
                    "prague castle",
                    "radio city music hall",
                    "statue of liberty",
                    "st. peter's square",
                    "the capitol rotunda",
                    "the churchill hotel",
                    "the getty center",
                    "tidal basin",
                    "universal studios hollywood",
                    "walt disney world",
                    "westminster abbey",
                    "acorn worm",
                    "african violet",
                    "american alligator",
                    "arctic fox",
                    "african elephant",
                    "anaconda",
                    "australian shepherd",
                    "barracuda",
                    "boll weevil",
                    "border terrier",
                    "brown bear",
                    "canaan dog",
                    "cherry blossoms",
                    "chocolate lab",
                    "dalmatian",
                    "eels & stingrays",
                    "evergreen tree",
                    "fruit tree",
                    "long-legged flamingo",
                    "giant schnauzer",
                    "great white shark",
                    "greyhound",
                    "iguana",
                    "miniature schnauzer",
                    "moose & caribou",
                    "pomeranian",
                    "puffin",
                    "red poppy",
                    "scarlet oak",
                    "siberian husky",
                    "tall elm trees",
                    "tamed lions",
                    "the family pet",
                    "squirrel monkey",
                    "whippet",
                    "wood thrush",
                    "colorful fish",
                    "dachshunds",
                    "all about eve",
                    "angels & demons",
                    "a beautiful mind",
                    "back to the future",
                    "city slickers",
                    "planet of the apes",
                    "the talented mr. ripley",
                    "attorney general",
                    "archivist",
                    "brain surgeon",
                    "chemist",
                    "court reporter",
                    "driving instructor",
                    "judge",
                    "lawyer",
                    "lumberjack",
                    "music teacher",
                    "personal trainer",
                    "public defender",
                    "recreation worker",
                    "webmaster",
                    "arabian sea",
                    "albany new york",
                    "allegheny mountains",
                    "boulder city nevada",
                    "british columbia",
                    "buffalo national river",
                    "capital beltway",
                    "c & o canal",
                    "denver colorado",
                    "embassy row",
                    "fairbanks alaska",
                    "fairbanks & ketchikan",
                    "guatemala",
                    "greenland & iceland",
                    "haight-ashbury",
                    "harlem river",
                    "lake erie",
                    "lake michigan",
                    "los angeles",
                    "louisville kentucky",
                    "lower manhattan",
                    "malibu",
                    "maryland",
                    "montana",
                    "montgomery alabama",
                    "nantucket sound",
                    "new brunswick canada",
                    "newark new jersey",
                    "new york city",
                    "ohio drive",
                    "ohio river",
                    "padre island",
                    "park avenue",
                    "portland oregon",
                    "seattle washington",
                    "times square",
                    "tampa florida",
                    "the bahamas",
                    "ottawa canada",
                    "pennsylvania avenue",
                    "potomac river",
                    "saint lawrence river",
                    "southeastern florida",
                    "sunny california",
                    "the city of cambridge",
                    "upper west side",
                    "vancouver",
                    "venice italy",
                    "altar boy",
                    "altar girl",
                    "bicycle messenger",
                    "bystander",
                    "biographer",
                    "busybody",
                    "campaign manager",
                    "certified technician",
                    "chief of staff",
                    "cocktail waitress",
                    "colonial history buff",
                    "cia agent",
                    "civil war buff",
                    "daddy's little girl",
                    "doubting thomas",
                    "expert archer",
                    "first baseman",
                    "fbi agent",
                    "first lady",
                    "folk hero",
                    "graffiti artist",
                    "great grandchild",
                    "gold medal winner",
                    "gymnast",
                    "high roller",
                    "jackpot winner",
                    "junior lifeguard",
                    "junior senator",
                    "journalism student",
                    "longtime subscriber",
                    "law student",
                    "left fielder",
                    "medical doctor",
                    "matron of honor",
                    "natural redhead",
                    "olympic swimmer",
                    "old friend",
                    "platoon leader",
                    "public speaker",
                    "school counselor",
                    "southpaw",
                    "senior official",
                    "stage mother",
                    "star performer",
                    "speaker of the house",
                    "steady boyfriend",
                    "trained athlete",
                    "woodcarver",
                    "wet blanket",
                    "a good fit",
                    "a great buy",
                    "ahead of the game",
                    "all operators are busy",
                    "as red as a beet",
                    "avoid the pitfalls",
                    "a gripping page turner",
                    "all kinds of things to do",
                    "big-cty diversity",
                    "back to square one",
                    "back to basics",
                    "bonjour!",
                    "built to last",
                    "coast-to-coast",
                    "coming unglued",
                    "call for directions",
                    "coming on like gangbusters",
                    "closed for renovations",
                    "cultural center of the country",
                    "do you speak french?",
                    "drawing a blank",
                    "don't spoil your dinner",
                    "explain yourself",
                    "fading away",
                    "family fun",
                    "fall in love with this city",
                    "fire up the grill",
                    "full-bodied flavor",
                    "give me a hint",
                    "going halfway",
                    "going the distance",
                    "growing up",
                    "having a green thumb",
                    "hail to the chief",
                    "have a bite to eat",
                    "here we go again",
                    "i was born ready",
                    "in the limelight",
                    "it never even crossed my mind",
                    "it's all in a day's work",
                    "i've got a hunch",
                    "it's a dirty shame",
                    "i've learned my lesson",
                    "just chillin'",
                    "keep your cool",
                    "keep your nose clean",
                    "lay it on thick",
                    "mix and match",
                    "mint condition",
                    "never say never",
                    "never in my wildest dreams",
                    "once in a blue moon",
                    "open up a can of worms",
                    "picture this",
                    "pick a card any card",
                    "pure coincidence",
                    "raising cain",
                    "rake over the coals",
                    "ready when you are",
                    "return to paradise",
                    "season to taste",
                    "seating is limited",
                    "shaken not stirred",
                    "share and share alike",
                    "stop building castles in the sky",
                    "standing room only",
                    "some assembly required",
                    "sweet sixteen and never been kissed",
                    "the truth shall set you free",
                    "take care",
                    "time for miracles",
                    "thanks a million",
                    "they never knew what hit them",
                    "throwing your money around",
                    "two of a kind",
                    "up-and-coming",
                    "walk it off",
                    "without spending an arm & a leg",
                    "wish you were here",
                    "work smarter not harder",
                    "way to go!",
                    "you're pushing my buttons",
                    "your message has been sent",
                    "your heart is in the right place",
                    "you took the words right out of my mouth",
                    "zoom in",
                    "a faraway land",
                    "abandoned warehouse",
                    "accredited college",
                    "aloha state",
                    "amazon rainforest",
                    "artist's loft",
                    "a city with great history",
                    "art museum",
                    "bilingual city",
                    "brownstone",
                    "bungalow",
                    "bustling city",
                    "campground",
                    "corner newsstand",
                    "captivating city",
                    "city that's a pleasure for everyone",
                    "culinary school",
                    "convenient location",
                    "dense tropical jungle",
                    "deluxe suite",
                    "department store",
                    "fabulous roadside attraction",
                    "factory outlet mall",
                    "famous restaurant",
                    "food court",
                    "french bistro",
                    "gas station",
                    "giant toy store",
                    "golf clubhouse",
                    "guesthouse",
                    "indoor garden",
                    "inland waterway",
                    "korean barbecue restaurant",
                    "large metropolitan area",
                    "log house",
                    "lush green forest",
                    "molokini",
                    "middle school",
                    "oval office",
                    "paved driveway",
                    "picnic pavilion",
                    "private gym",
                    "private residence",
                    "r.f.k. stadium",
                    "romantic spot",
                    "reflecting pool",
                    "sculpture garden",
                    "sporting goods store",
                    "seaport district",
                    "the capital of italy",
                    "the capital of germany",
                    "tropical paradise",
                    "trout stream",
                    "the west wing",
                    "tinseltown",
                    "upscale hotel",
                    "video arcade",
                    "victorian home",
                    "wedding chapel",
                    "white sand beach",
                    "world's longest street",
                    "wraparound porch",
                    "white house lawn",
                    "wine country",
                    "aquatic gardens",
                    "age-old churches",
                    "art gallery",
                    "ancient temples",
                    "botanical gardens",
                    "back alley",
                    "boutique",
                    "breathtaking canadian city",
                    "busy streets",
                    "coffee shops",
                    "capital city of france",
                    "churches and synagogues",
                    "colleges & universities",
                    "coastal meadows",
                    "corner office",
                    "covered porch",
                    "diverse restaurants",
                    "flawless sandy beaches",
                    "great restaurants",
                    "gothic cathedrals",
                    "humid lowland jungles",
                    "historical sites",
                    "ivy league colleges",
                    "marine barracks",
                    "museum mile",
                    "narrow cobblestone streets",
                    "neoclassical buildings",
                    "nightclubs",
                    "playground",
                    "row houses",
                    "state capitals",
                    "school cafeteria",
                    "taco stand",
                    "the appian way",
                    "the gulf coast",
                    "the skydeck at willis tower",
                    "tribal lands",
                    "trendy shops",
                    "whitewashed hotels",
                    "world-famous parks & attractions",
                    "air force one",
                    "american stock exchange",
                    "basketball star allen iverson",
                    "ben stiller",
                    "ben affleck",
                    "buzz aldrin",
                    "boston bruins",
                    "bill of rights",
                    "bugsy siegel",
                    "calgary flames",
                    "composer johann sebastian bach",
                    "eli manning",
                    "frederick douglass",
                    "james earl jones",
                    "jeremy sisto",
                    "jimmy fallon",
                    "kevin dillon",
                    "larry bird",
                    "lance burton",
                    "marvel comics",
                    "mark harmon",
                    "monty python",
                    "mel brooks",
                    "michelle obama",
                    "mona lisa",
                    "neil patrick harris",
                    "neil simon",
                    "prince harry",
                    "purdue university",
                    "ryan phillippe",
                    "san francisco giants",
                    "singer tim mcgraw",
                    "survivor host jeff probst",
                    "the velvet underground",
                    "the bradford exchange",
                    "the rolling stones",
                    "the yankees",
                    "tiki barber",
                    "u.s. air force academy",
                    "u.s. department of education",
                    "united states coast guard",
                    "utah jazz",
                    "washington nationals",
                    "washington redskins",
                    "adam & eve",
                    "basketball star lebron james",
                    "boston red sox",
                    "bradley cooper",
                    "cirque du soleil",
                    "denzel washington",
                    "national basketball league",
                    "orville & wilbur wright",
                    "university of notre dame",
                    "a pocketful of rye",
                    "a picture is worth a thousand words",
                    "call me ishmael",
                    "good grief charlie brown",
                    "jack be quick",
                    "little b0-peep has lost her sheep",
                    "london bridge is falling down",
                    "all-star cast",
                    "cameras rolling",
                    "documentary film",
                    "film review",
                    "may i have a drumroll please?",
                    "musical comedy",
                    "open audition",
                    "season finale",
                    "singing sensation",
                    "stage actors",
                    "i did it my way",
                    "one for the money two for the show",
                    "dedicated to the one i love",
                    "a friendly reminder",
                    "a pleasant surprise",
                    "a brisk pace",
                    "a sharp pencil",
                    "aches & pains",
                    "american flag",
                    "archery",
                    "alpine glaciers",
                    "assembly line",
                    "aircraft carrier",
                    "an amazing view of the skyline",
                    "bright blue sky",
                    "battleship",
                    "batting helmet",
                    "birthday present",
                    "big decision",
                    "blue ribbon",
                    "bookmark",
                    "corncob pipe",
                    "calypso music",
                    "chainsaw",
                    "color printer",
                    "classical music",
                    "computer software",
                    "dazzling nightlife",
                    "designer luggage",
                    "dotted line",
                    "double coupons",
                    "engraved invitations",
                    "eyelash curler",
                    "engaging conversation",
                    "eyebrow pencil",
                    "fighter jet",
                    "floodlight",
                    "favorable climate",
                    "fine dining",
                    "fleeting moment",
                    "fond memories",
                    "freight elevator",
                    "fun hobby",
                    "good publicity",
                    "guilty pleasure",
                    "good judgment",
                    "good luck charm",
                    "great personality",
                    "hardback book",
                    "healing massage",
                    "hd digital camera",
                    "hooded sweatshirt",
                    "humble honor",
                    "icy snowbank",
                    "jean jacket",
                    "junior college football",
                    "jumbo snowflakes",
                    "leading national brands",
                    "leisure suit",
                    "lighting displays",
                    "linen handkerchief",
                    "life savings",
                    "loft bed",
                    "lunch money",
                    "lifetime warranty",
                    "mild weather",
                    "magazine article",
                    "membership dues",
                    "minimum wage",
                    "modern art",
                    "mud flaps",
                    "math quiz",
                    "monuments",
                    "natural ability",
                    "natural habitat",
                    "naval fleet",
                    "overnight delivery",
                    "perfect report card",
                    "pirate booty",
                    "padlock",
                    "pilots license",
                    "pleasant conversation",
                    "pretty smiles",
                    "presidential seal",
                    "quick rundown",
                    "radio station",
                    "radio tuner",
                    "resort vacation",
                    "saddlebag",
                    "savings account",
                    "scaffold",
                    "senatorial gavel",
                    "spare key",
                    "sparkling skyline",
                    "spectacular sunset",
                    "sunny forecast",
                    "starting revelation",
                    "substantive argument",
                    "subway system",
                    "tempting offer",
                    "tree trunk",
                    "the constitution",
                    "the soothing sound of the waves",
                    "tiki statue",
                    "thunderous round of applause",
                    "toll-free customer service number",
                    "totem pole",
                    "trendy hairstyle",
                    "unique urban experience",
                    "unique buildings",
                    "up tempo",
                    "vacation of my dreams",
                    "winning ticket",
                    "winning streak",
                    "wrapped presents",
                    "warm and sunny climate",
                    "warm weather",
                    "water slide",
                    "witch's potion",
                    "wooden toy box",
                    "wooden ukulele",
                    "action figures",
                    "acres of land",
                    "adverse conditions",
                    "alkaline batteries",
                    "amazing hikes",
                    "architectural treasures",
                    "blue skies",
                    "business hours",
                    "cartilage & vertebrae",
                    "colorful embroidered blouses",
                    "diverse cultures",
                    "emergency supplies",
                    "engraved invitations",
                    "fond memories",
                    "funky gadgets",
                    "fingerprints",
                    "holiday ornaments",
                    "hot humid summers",
                    "lucky numbers",
                    "major issues",
                    "masking tape",
                    "meows & woofs",
                    "metal sculptures",
                    "monuments",
                    "on-campus activities",
                    "outdoor activities",
                    "rosy cheeks",
                    "short stories",
                    "solar panels",
                    "striking similarities",
                    "skyscrapers",
                    "strengths and weaknesses",
                    "stony coral reefs",
                    "summer wardrobe",
                    "strict guidelines",
                    "sun-kissed cheeks",
                    "tickets to a rock concert",
                    "table manners",
                    "tickets to a miami heat game",
                    "unique buildings",
                    "unique islands",
                    "warm sunshine",
                    "waterfalls",
                    "a christmas carol",
                    "alice's adventures in wonderland",
                    "all that jazz",
                    "detroit free press",
                    "good housekeeping",
                    "gq magazine",
                    "i know why the caged bird sings",
                    "jersey boys",
                    "rolling stone magazine",
                    "the arizona republic",
                    "the washington post",
                    "the world almanac for kids",
                    "the three little pigs",
                    "family guy",
                    "how i met your mother",
                    "men of a certain age",
                    "so you think you can dance",
                    "the cleveland show",
                    "the real housewives of new york city",
                    "attending wimbledon",
                    "buying a new coat",
                    "buying tacos from a street vendor",
                    "cooking freshly caught fish",
                    "collecting seashells",
                    "dancing in the sand",
                    "digging my toes in the sand",
                    "adiscovering canadian art",
                    "dusting my desk",
                    "eating raw vegetables",
                    "enjoying a romantic view of the city",
                    "enjoying the view from nob hill",
                    "feeding the ducks at the public garden",
                    "flying to a foreign country",
                    "going to the ballet",
                    "gargling with mouthwash",
                    "getting goosebumps",
                    "going for a bike ride",
                    "going to the gym",
                    "going to a nightclub",
                    "hailing a cab",
                    "kayaking in the bay",
                    "learning to hula",
                    "listening to the chimes of big ben",
                    "painting a picture",
                    "painting the house",
                    "panning for gold",
                    "relaxing poolside",
                    "remodeling the kitchen",
                    "sending thank you notes",
                    "shopping in soho",
                    "snorkeling in clear blue water",
                    "staying in a beach bungalow",
                    "scrubbing the floor",
                    "speaking french and english",
                    "standing in my bare feet",
                    "shaking hands with minnie mouse",
                    "shopping at the antique fair",
                    "spending the day hiking in the mountains",
                    "seeing a movie",
                    "shining my shoes",
                    "standing in line",
                    "sunning myself on the beach",
                    "taking in an afternoon movie",
                    "taking a day trip to kissimmee",
                    "taking it easy",
                    "taking a day trip to the beach",
                    "telling tall tales",
                    "touring the island on horseback",
                    "traveling in a snowmobile",
                    "visiting the zoo",
                    "visiting the old royal palace",
                    "watching the hockey game",
                    "wiping off my shoes",
                    "zooming down a water slide"};

string phrasesSpaced[] = {"a d d r e s s  b o o k",
                      "a f t e r - s h a v e  l o t i o n",
                      "b o o k s h e l f",
                      "b e a n  b a g  c h a i r",
                      "b o o k e n d s",
                      "c e r a m i c  b o w l",
                      "c i t r u s - s c e n t e d  s h o w e r  g e l",
                      "e l e c t r i c  t o o t h b r u s h",
                      "f i s h i n g  t a c k l e  b o x",
                      "h o m e  o f f i c e",
                      "j e w e l  b o x",
                      "l a v a  l a m p",
                      "l i n e n  n a p k i n s",
                      "m o u s e p a d",
                      "o a k  c h i n a  c a b i n e t",
                      "p o l i s h i n g  w a x",
                      "p e n s  a n d  p e n c i l s",
                      "p h o t o  a l b u m",
                      "p r o f i c i e n t l y  d i s p l a y e d  a w a r d s",
                      "p r u n i n g  s h e a r s",
                      "r e c l i n i n g  l o u n g e  c h a i r",
                      "s h a m p o o  & c o n d i t i o n e r",
                      "s t u r d y  t a b l e",
                      "w i n d o w  s c r e e n s",
                      "w o o d e n  t a b l e",
                      "b a b b i t t",
                      "c a t ' s  c r a d l e",
                      "j a n e  e y r e",
                      "t h e  b i g  s l e e p",
                      "t h e  s c a r l e t  l e t t e r",
                      "t h e  h o u s e  o f  m i r t h",
                      "t h e  s o u t h  b e a c h  d i e t",
                      "a n  a m e r i c a n  i n  p a r i s",
                      "c a s a b l a n c a",
                      "s o u t h  p a c i f i c",
                      "t h e  b l o b",
                      "t h e  d i r t y  d o z e n",
                      "a l i c e ,  f l o ,  v e r n ,  & m e l",
                      "b o n a n z a",
                      "b u l l  t h e  b a i l i f f",
                      "d o n  j o h n s o n  s t a r s  i n  m i a m i  v i c e",
                      "f  t r o o p",
                      "h o w a r d  & m a r i o n  c u n n i n g h a m",
                      "h a w a i i  f i v e - o",
                      "m a r c i a !  m a r c i a !  m a r c i a ! ",
                      "m i a m i  v i c e",
                      "a  s i d e  t r i p  t o  o x f o r d  u n i v e r s i t y",
                      "a  c r u i s e  t o  t h e  i s l a n d",
                      "a c t  o f  c o n g r e s s",
                      "b o n f i r e",
                      "b i g  b a s h",
                      "c a r i b b e a n  v a c a t i o n",
                      "c a t a m a r a n  s a i l i n g  c r u i s e",
                      "c i n c o  d e  m a y o",
                      "c a t e r e d  p a r t y",
                      "d a z z l i n g  s u n s e t",
                      "f a m i l y  r e u n i o n",
                      "f i s h i n g  t o u r n a m e n t",
                      "f o r m a l  d i n n e r",
                      "h a r b o r  c r u i s e",
                      "h i g h  s c h o o l  r e u n i o n",
                      "h o l i d a y  p a r a d e",
                      "i n d e p e n d e n c e  d a y",
                      "i n t e r n a t i o n a l  f l i g h t",
                      "l e a p  y e a r",
                      "l o s  a n g e l e s  m a r a t h o n",
                      "m a r r i a g e  c e r e m o n y",
                      "m e m o r i a l  d a y",
                      "o p e n i n g  n i g h t",
                      "o p e n  h o u s e",
                      "p i v o t a l  m o m e n t",
                      "p r e s i d e n t i a l  d e b a t e",
                      "p r i v a t e  t o u r",
                      "r e e f  d i v i n g",
                      "r u n n i n g  a  m a r a t h o n",
                      "s a l t w a t e r  f i s h i n g  t r i p",
                      "s c h o o l  c h r i s t m a s  p a g e a n t",
                      "s p r i n g  w h i t e  s a l e",
                      "s u n n y  a f t e r n o o n",
                      "t o u r i n g  t h e  w i n d y  c i t y",
                      "t r a v e l  e x p o",
                      "u n f o r g e t t a b l e  v a c a t i o n",
                      "a  c r u i s e  t h r o u g h  g l a c i e r  b a y",
                      "a l l - e x p e n s e s  p a i d  v a c a t i o n",
                      "a n n u a l  m e e t i n g",
                      "a n n u a l  s a l e",
                      "b o a r d r o o m  m e e t i n g",
                      "b u s i n e s s  c o n v e n t i o n",
                      "c a m p i n g  r o a d  t r i p",
                      "c a r i b b e a n  g e t a w a y",
                      "c o m i c  b o o k  c o n v e n t i o n",
                      "d a r i n g  p a r a c h u t e  j u m p",
                      "d o g  d a y s  o f  s u m m e r",
                      "g r a n d  t o u r",
                      "h a r b o r  c r u i s e",
                      "h o l i d a y  w e e k e n d",
                      "h u m i d  w e a t h e r",
                      "i d e a l  v a c a t i o n",
                      "i n d e p e n d e n c e  d a y",
                      "i n v i g o r a t i n g  w a l k",
                      "j o b  f a i r",
                      "o c e a n - v i e w  d i n i n g",
                      "p r i v a t e  t o u r",
                      "s a i l b o a t  r a c e",
                      "s a n d s t o r m",
                      "s i g h t s e e i n g  c r u i s e",
                      "s p e l l i n g  b e e",
                      "s h o w s  w i t h  s p e c t a c u l a r  s t u n t s",
                      "s u n n y  w a r m  w e e k e n d",
                      "s t a t e  d i n n e r",
                      "s u m m e r  v a c a t i o n",
                      "w a t e r f r o n t  d i n i n g",
                      "w i l d - g o o s e  c h a s e",
                      "g o d f a t h e r  & g o d m o t h e r",
                      "p a r i s  a n d  n i c k y  h i l t o n",
                      "w i l l  & w i l l o w  s m i t h",
                      "e e y o r e  & t i g g e r",
                      "e b e n e z e r  s c r o o g e",
                      "f r e d  f l i n t s t o n e",
                      "h e r c u l e s",
                      "h o m e r  s i m p s o n",
                      "j a c o b  m a r l e y",
                      "n i c k  f u r y",
                      "o l d  k i n g  c o l e",
                      "s a n t a ' s  e l v e s",
                      "t h e  i n c r e d i b l e  h u l k",
                      "t h e  g r e e n  l a n t e r n",
                      "t o p  c a t",
                      "t w e e d l e d u m",
                      "t h e  c a t  i n  t h e  h a t",
                      "v e g a s  v i c",
                      "a m e r i c a n  c h e d d a r  c h e e s e",
                      "b a k e d  f r u i t  c o m p o t e",
                      "b e a n  d i p",
                      "b a g e l s  a n d  l o x",
                      "b e a n s  & c o r n b r e a d",
                      "b o t t l e d  w a t e r",
                      "b u f f a l o  b u r g e r",
                      "b u t t e r h e a d  l e t t u c e",
                      "b a s i l  l e a v e s",
                      "c h i c k e n  q u e s a d i l l a s",
                      "c e l e r y  r o o t  s a l a d",
                      "c h o c o l a t e  s y r u p",
                      "c o o l  t r e a t s",
                      "c h e e s e  p i z z a",
                      "c h o c o l a t e  t o f f e e",
                      "c r e a m y  r i c o t t a  c h e e s e",
                      "c h i c k e n  s a l a d",
                      "c h o c o l a t e  m o u s s e",
                      "d e e p - d i s h  p i z z a",
                      "d e l i c i o u s  c u i s i n e",
                      "d e l i  s a n d w i c h",
                      "d e e p - d i s h  p e a c h  p i e",
                      "e a r  o f  c o r n",
                      "e m p a n a d a s",
                      "e n g l i s h  t o f f e e",
                      "f r e s h  f r u i t  p l a t t e r",
                      "f r e s h  p a r s n i p s",
                      "f r e s h  p i n e a p p l e  j u i c e",
                      "f r i e d  s e a f o o d  p l a t t e r",
                      "f r u i t  c o c k t a i l",
                      "f r e n c h  f r i e s",
                      "g a l a  a p p l e s",
                      "g r e e n  t u r t l e  s o u p",
                      "g r e e n  c o r n  t a m a l e s",
                      "g r a n d m a ' s  f r u i t c a k e",
                      "h o m e m a d e  p a s t a",
                      "h a b a n e r o  s a u c e",
                      "h a w a i i a n  f e a s t",
                      "h u e v o s  r a n c h e r o s",
                      "j u i c y  p i n e a p p l e",
                      "k o s h e r  s a l t",
                      "k e y  l i m e  p i e",
                      "l e m o n - g a r l i c  c h i c k e n",
                      "l e m o n  d r o p s",
                      "l e m o n  p o p p y  s e e d  m u f f i n s",
                      "l i v e r  d u m p l i n g s",
                      "m i l k  c h o c o l a t e  b a r",
                      "m i n c e m e a t  p i e",
                      "n a c h o s  s u p r e m e",
                      "o k r a  s a l a d",
                      "o r g a n i c  b r a z i l  n u t s",
                      "o v e n - f r i e d  c h i c k e n",
                      "o y s t e r s  o n  t h e  h a l f  s h e l l",
                      "p a s t a  w i t h  p a r m e s a n  c h e e s e",
                      "p e a c h  t e a",
                      "p a n  g r a v y",
                      "p o a c h e d  p a r e d  f r u i t",
                      "p e p p e r m i n t  c a n d y  c a n e",
                      "r e d  v e l v e t  c a k e",
                      "r i p e  b a n a n a s",
                      "r h u b a r b  p i e",
                      "s a l a d  v e g e t a b l e s",
                      "s a u s a g e  a n d  p o t a t o e s",
                      "s e a r e d  p o r k",
                      "s h e p h e r d ' s  p i e",
                      "s e a f o o d  t e t r a z z i n i",
                      "s k i n n e d  t a n g e l o",
                      "s m o k e d  h a m",
                      "s m o k e d  t r o u t",
                      "s p i c y  c o c k t a i l  s a u c e",
                      "s e e d l e s s  w a t e r m e l o n",
                      "t h i n - c r u s t  p i z z a",
                      "t e a  a n d  c r u m p e t s",
                      "t h o m p s o n  s e e d l e s s  g r a p e s",
                      "t u n a  s a l a d  s a n d w i c h",
                      "v e g e t a b l e  j u i c e",
                      "v e g e t a b l e  s o u p",
                      "w e d d i n g  c a k e",
                      "y e l l o w  b e l l  p e p p e r s",
                      "a r m  w r e s t l i n g",
                      "a f t e r s c h o o l  a c t i v i t i e s",
                      "a  d i p  i n  t h e  p o o l",
                      "b a l l o o n  a n i m a l s",
                      "b e l l y  d a n c i n g",
                      "c a t c h i n g  a  w a v e",
                      "c r o s s - c o u n t r y  s k i i n g",
                      "j o u s t i n g",
                      "k a y a k  p o l o",
                      "k n i g h t  b i s h o p  & p a w n",
                      "m o v i e  s t u d i o  t o u r",
                      "m o d e l i n g  c l a y",
                      "o c e a n  k a y a k",
                      "p o k e r  c h i p s",
                      "p l a y i n g  i c e  h o c k e y",
                      "p l a y i n g  s t i c k b a l l",
                      "r a c q u e t b a l l",
                      "r o c k  c l i m b i n g",
                      "s l o t  m a c h i n e",
                      "t h u m b  w r e s t l i n g",
                      "t r o l l e y  t o u r",
                      "v i d e o  p o k e r",
                      "a l u m i n u m  c h e e s e  g r a t e r",
                      "g l a s s  b o w l",
                      "b a k i n g  d i s h",
                      "c a n n e d  g o o d s",
                      "c o n i c a l  s t r a i n e r",
                      "c o n v e n t i o n a l  o v e n",
                      "d r i n k i n g  s t r a w s",
                      "g r a v y  l a d l e",
                      "i n s u l a t e d  t e a p o t",
                      "l e m o n  a n d  l i m e  s q u e e z e r",
                      "s t a n d  m i x e r",
                      "a r l i n g t o n  h o u s e",
                      "b u n k e r  h i l l  m o n u m e n t",
                      "c a p i t o l  h i l l",
                      "c i r c u s  c i r c u s",
                      "d e n a l i  n a t i o n a l  p a r k",
                      "f r e m o n t  s t r e e t",
                      "g r e a t  s a n d  d u n e s  n a t i o n a l  p a r k",
                      "h o o v e r  d a m",
                      "j u d i c i a r y  s q u a r e",
                      "l i b e r a c e  m u s e u m",
                      "l u x o r ' s  p y r a m i d",
                      "m a d i s o n  s q u a r e  g a r d e n",
                      "m e m o r i a l  b r i d g e",
                      "m u s c l e  b e a c h",
                      "n a t i o n a l  a r b o r e t u m",
                      "n a t i o n a l  g a l l e r y  o f  a r t",
                      "n a t i o n a l  m a l l",
                      "p e n n  s t a t i o n",
                      "p r a g u e  c a s t l e",
                      "r a d i o  c i t y  m u s i c  h a l l",
                      "s t a t u e  o f  l i b e r t y",
                      "s t . p e t e r ' s  s q u a r e",
                      "t h e  c a p i t o l  r o t u n d a",
                      "t h e  c h u r c h i l l  h o t e l",
                      "t h e  g e t t y  c e n t e r",
                      "t i d a l  b a s i n",
                      "u n i v e r s a l  s t u d i o s  h o l l y w o o d",
                      "w a l t  d i s n e y  w o r l d",
                      "w e s t m i n s t e r  a b b e y",
                      "a c o r n  w o r m",
                      "a f r i c a n  v i o l e t",
                      "a m e r i c a n  a l l i g a t o r",
                      "a r c t i c  f o x",
                      "a f r i c a n  e l e p h a n t",
                      "a n a c o n d a",
                      "a u s t r a l i a n  s h e p h e r d",
                      "b a r r a c u d a",
                      "b o l l  w e e v i l",
                      "b o r d e r  t e r r i e r",
                      "b r o w n  b e a r",
                      "c a n a a n  d o g",
                      "c h e r r y  b l o s s o m s",
                      "c h o c o l a t e  l a b",
                      "d a l m a t i a n",
                      "e e l s  & s t i n g r a y s",
                      "e v e r g r e e n  t r e e",
                      "f r u i t  t r e e",
                      "l o n g - l e g g e d  f l a m i n g o",
                      "g i a n t  s c h n a u z e r",
                      "g r e a t  w h i t e  s h a r k",
                      "g r e y h o u n d",
                      "i g u a n a",
                      "m i n i a t u r e  s c h n a u z e r",
                      "m o o s e  & c a r i b o u",
                      "p o m e r a n i a n",
                      "p u f f i n",
                      "r e d  p o p p y",
                      "s c a r l e t  o a k",
                      "s i b e r i a n  h u s k y",
                      "t a l l  e l m  t r e e s",
                      "t a m e d  l i o n s",
                      "t h e  f a m i l y  p e t",
                      "s q u i r r e l  m o n k e y",
                      "w h i p p e t",
                      "w o o d  t h r u s h",
                      "c o l o r f u l  f i s h",
                      "d a c h s h u n d s",
                      "a l l  a b o u t  e v e",
                      "a n g e l s  & d e m o n s",
                      "a  b e a u t i f u l  m i n d",
                      "b a c k  t o  t h e  f u t u r e",
                      "c i t y  s l i c k e r s",
                      "p l a n e t  o f  t h e  a p e s",
                      "t h e  t a l e n t e d  m r . r i p l e y",
                      "a t t o r n e y  g e n e r a l",
                      "a r c h i v i s t",
                      "b r a i n  s u r g e o n",
                      "c h e m i s t",
                      "c o u r t  r e p o r t e r",
                      "d r i v i n g  i n s t r u c t o r",
                      "j u d g e",
                      "l a w y e r",
                      "l u m b e r j a c k",
                      "m u s i c  t e a c h e r",
                      "p e r s o n a l  t r a i n e r",
                      "p u b l i c  d e f e n d e r",
                      "r e c r e a t i o n  w o r k e r",
                      "w e b m a s t e r",
                      "a r a b i a n  s e a",
                      "a l b a n y  n e w  y o r k",
                      "a l l e g h e n y  m o u n t a i n s",
                      "b o u l d e r  c i t y  n e v a d a",
                      "b r i t i s h  c o l u m b i a",
                      "b u f f a l o  n a t i o n a l  r i v e r",
                      "c a p i t a l  b e l t w a y",
                      "c  & o  c a n a l",
                      "d e n v e r  c o l o r a d o",
                      "e m b a s s y  r o w",
                      "f a i r b a n k s  a l a s k a",
                      "f a i r b a n k s  & k e t c h i k a n",
                      "g u a t e m a l a",
                      "g r e e n l a n d  & i c e l a n d",
                      "h a i g h t - a s h b u r y",
                      "h a r l e m  r i v e r",
                      "l a k e  e r i e",
                      "l a k e  m i c h i g a n",
                      "l o s  a n g e l e s",
                      "l o u i s v i l l e  k e n t u c k y",
                      "l o w e r  m a n h a t t a n",
                      "m a l i b u",
                      "m a r y l a n d",
                      "m o n t a n a",
                      "m o n t g o m e r y  a l a b a m a",
                      "n a n t u c k e t  s o u n d",
                      "n e w  b r u n s w i c k  c a n a d a",
                      "n e w a r k  n e w  j e r s e y",
                      "n e w  y o r k  c i t y",
                      "o h i o  d r i v e",
                      "o h i o  r i v e r",
                      "p a d r e  i s l a n d",
                      "p a r k  a v e n u e",
                      "p o r t l a n d  o r e g o n",
                      "s e a t t l e  w a s h i n g t o n",
                      "t i m e s  s q u a r e",
                      "t a m p a  f l o r i d a",
                      "t h e  b a h a m a s",
                      "o t t a w a  c a n a d a",
                      "p e n n s y l v a n i a  a v e n u e",
                      "p o t o m a c  r i v e r",
                      "s a i n t  l a w r e n c e  r i v e r",
                      "s o u t h e a s t e r n  f l o r i d a",
                      "s u n n y  c a l i f o r n i a",
                      "t h e  c i t y  o f  c a m b r i d g e",
                      "u p p e r  w e s t  s i d e",
                      "v a n c o u v e r",
                      "v e n i c e  i t a l y",
                      "a l t a r  b o y",
                      "a l t a r  g i r l",
                      "b i c y c l e  m e s s e n g e r",
                      "b y s t a n d e r",
                      "b i o g r a p h e r",
                      "b u s y b o d y",
                      "c a m p a i g n  m a n a g e r",
                      "c e r t i f i e d  t e c h n i c i a n",
                      "c h i e f  o f  s t a f f",
                      "c o c k t a i l  w a i t r e s s",
                      "c o l o n i a l  h i s t o r y  b u f f",
                      "c i a  a g e n t",
                      "c i v i l  w a r  b u f f",
                      "d a d d y ' s  l i t t l e  g i r l",
                      "d o u b t i n g  t h o m a s",
                      "e x p e r t  a r c h e r",
                      "f i r s t  b a s e m a n",
                      "f b i  a g e n t",
                      "f i r s t  l a d y",
                      "f o l k  h e r o",
                      "g r a f f i t i  a r t i s t",
                      "g r e a t  g r a n d c h i l d",
                      "g o l d  m e d a l  w i n n e r",
                      "g y m n a s t",
                      "h i g h  r o l l e r",
                      "j a c k p o t  w i n n e r",
                      "j u n i o r  l i f e g u a r d",
                      "j u n i o r  s e n a t o r",
                      "j o u r n a l i s m  s t u d e n t",
                      "l o n g t i m e  s u b s c r i b e r",
                      "l a w  s t u d e n t",
                      "l e f t  f i e l d e r",
                      "m e d i c a l  d o c t o r",
                      "m a t r o n  o f  h o n o r",
                      "n a t u r a l  r e d h e a d",
                      "o l y m p i c  s w i m m e r",
                      "o l d  f r i e n d",
                      "p l a t o o n  l e a d e r",
                      "p u b l i c  s p e a k e r",
                      "s c h o o l  c o u n s e l o r",
                      "s o u t h p a w",
                      "s e n i o r  o f f i c i a l",
                      "s t a g e  m o t h e r",
                      "s t a r  p e r f o r m e r",
                      "s p e a k e r  o f  t h e  h o u s e",
                      "s t e a d y  b o y f r i e n d",
                      "t r a i n e d  a t h l e t e",
                      "w o o d c a r v e r",
                      "w e t  b l a n k e t",
                      "a  g o o d  f i t",
                      "a  g r e a t  b u y",
                      "a h e a d  o f  t h e  g a m e",
                      "a l l  o p e r a t o r s  a r e  b u s y",
                      "a s  r e d  a s  a  b e e t",
                      "a v o i d  t h e  p i t f a l l s",
                      "a  g r i p p i n g  p a g e  t u r n e r",
                      "a l l  k i n d s  o f  t h i n g s  t o  d o",
                      "b i g - c t y  d i v e r s i t y",
                      "b a c k  t o  s q u a r e  o n e",
                      "b a c k  t o  b a s i c s",
                      "b o n j o u r ! ",
                      "b u i l t  t o  l a s t",
                      "c o a s t - t o - c o a s t",
                      "c o m i n g  u n g l u e d",
                      "c a l l  f o r  d i r e c t i o n s",
                      "c o m i n g  o n  l i k e  g a n g b u s t e r s",
                      "c l o s e d  f o r  r e n o v a t i o n s",
                      "c u l t u r a l  c e n t e r  o f  t h e  c o u n t r y",
                      "d o  y o u  s p e a k  f r e n c h ?",
                      "d r a w i n g  a  b l a n k",
                      "d o n ' t  s p o i l  y o u r  d i n n e r",
                      "e x p l a i n  y o u r s e l f",
                      "f a d i n g  a w a y",
                      "f a m i l y  f u n",
                      "f a l l  i n  l o v e  w i t h  t h i s  c i t y",
                      "f i r e  u p  t h e  g r i l l",
                      "f u l l - b o d i e d  f l a v o r",
                      "g i v e  m e  a  h i n t",
                      "g o i n g  h a l f w a y",
                      "g o i n g  t h e  d i s t a n c e",
                      "g r o w i n g  u p",
                      "h a v i n g  a  g r e e n  t h u m b",
                      "h a i l  t o  t h e  c h i e f",
                      "h a v e  a  b i t e  t o  e a t",
                      "h e r e  w e  g o  a g a i n",
                      "i  w a s  b o r n  r e a d y",
                      "i n  t h e  l i m e l i g h t",
                      "i t  n e v e r  e v e n  c r o s s e d  m y  m i n d",
                      "i t ' s  a l l  i n  a  d a y ' s  w o r k",
                      "i ' v e  g o t  a  h u n c h",
                      "i t ' s  a  d i r t y  s h a m e",
                      "i ' v e  l e a r n e d  m y  l e s s o n",
                      "j u s t  c h i l l i n ' ",
                      "k e e p  y o u r  c o o l",
                      "k e e p  y o u r  n o s e  c l e a n",
                      "l a y  i t  o n  t h i c k",
                      "m i x  a n d  m a t c h",
                      "m i n t  c o n d i t i o n",
                      "n e v e r  s a y  n e v e r",
                      "n e v e r  i n  m y  w i l d e s t  d r e a m s",
                      "o n c e  i n  a  b l u e  m o o n",
                      "o p e n  u p  a  c a n  o f  w o r m s",
                      "p i c t u r e  t h i s",
                      "p i c k  a  c a r d  a n y  c a r d",
                      "p u r e  c o i n c i d e n c e",
                      "r a i s i n g  c a i n",
                      "r a k e  o v e r  t h e  c o a l s",
                      "r e a d y  w h e n  y o u  a r e",
                      "r e t u r n  t o  p a r a d i s e",
                      "s e a s o n  t o  t a s t e",
                      "s e a t i n g  i s  l i m i t e d",
                      "s h a k e n  n o t  s t i r r e d",
                      "s h a r e  a n d  s h a r e  a l i k e",
                      "s t o p  b u i l d i n g  c a s t l e s  i n  t h e  s k y",
                      "s t a n d i n g  r o o m  o n l y",
                      "s o m e  a s s e m b l y  r e q u i r e d",
                      "s w e e t  s i x t e e n  a n d  n e v e r  b e e n  k i s s e d",
                      "t h e  t r u t h  s h a l l  s e t  y o u  f r e e",
                      "t a k e  c a r e",
                      "t i m e  f o r  m i r a c l e s",
                      "t h a n k s  a  m i l l i o n",
                      "t h e y  n e v e r  k n e w  w h a t  h i t  t h e m",
                      "t h r o w i n g  y o u r  m o n e y  a r o u n d",
                      "t w o  o f  a  k i n d",
                      "u p - a n d - c o m i n g",
                      "w a l k  i t  o f f",
                      "w i t h o u t  s p e n d i n g  a n  a r m  & a  l e g",
                      "w i s h  y o u  w e r e  h e r e",
                      "w o r k  s m a r t e r  n o t  h a r d e r",
                      "w a y  t o  g o ! ",
                      "y o u ' r e  p u s h i n g  m y  b u t t o n s",
                      "y o u r  m e s s a g e  h a s  b e e n  s e n t",
                      "y o u r  h e a r t  i s  i n  t h e  r i g h t  p l a c e",
                      "y o u  t o o k  t h e  w o r d s  r i g h t  o u t  o f  m y  m o u t h",
                      "z o o m  i n",
                      "a  f a r a w a y  l a n d",
                      "a b a n d o n e d  w a r e h o u s e",
                      "a c c r e d i t e d  c o l l e g e",
                      "a l o h a  s t a t e",
                      "a m a z o n  r a i n f o r e s t",
                      "a r t i s t ' s  l o f t",
                      "a  c i t y  w i t h  g r e a t  h i s t o r y",
                      "a r t  m u s e u m",
                      "b i l i n g u a l  c i t y",
                      "b r o w n s t o n e",
                      "b u n g a l o w",
                      "b u s t l i n g  c i t y",
                      "c a m p g r o u n d",
                      "c o r n e r  n e w s s t a n d",
                      "c a p t i v a t i n g  c i t y",
                      "c i t y  t h a t ' s  a  p l e a s u r e  f o r  e v e r y o n e",
                      "c u l i n a r y  s c h o o l",
                      "c o n v e n i e n t  l o c a t i o n",
                      "d e n s e  t r o p i c a l  j u n g l e",
                      "d e l u x e  s u i t e",
                      "d e p a r t m e n t  s t o r e",
                      "f a b u l o u s  r o a d s i d e  a t t r a c t i o n",
                      "f a c t o r y  o u t l e t  m a l l",
                      "f a m o u s  r e s t a u r a n t",
                      "f o o d  c o u r t",
                      "f r e n c h  b i s t r o",
                      "g a s  s t a t i o n",
                      "g i a n t  t o y  s t o r e",
                      "g o l f  c l u b h o u s e",
                      "g u e s t h o u s e",
                      "i n d o o r  g a r d e n",
                      "i n l a n d  w a t e r w a y",
                      "k o r e a n  b a r b e c u e  r e s t a u r a n t",
                      "l a r g e  m e t r o p o l i t a n  a r e a",
                      "l o g  h o u s e",
                      "l u s h  g r e e n  f o r e s t",
                      "m o l o k i n i",
                      "m i d d l e  s c h o o l",
                      "o v a l  o f f i c e",
                      "p a v e d  d r i v e w a y",
                      "p i c n i c  p a v i l i o n",
                      "p r i v a t e  g y m",
                      "p r i v a t e  r e s i d e n c e",
                      "r .f .k . s t a d i u m",
                      "r o m a n t i c  s p o t",
                      "r e f l e c t i n g  p o o l",
                      "s c u l p t u r e  g a r d e n",
                      "s p o r t i n g  g o o d s  s t o r e",
                      "s e a p o r t  d i s t r i c t",
                      "t h e  c a p i t a l  o f  i t a l y",
                      "t h e  c a p i t a l  o f  g e r m a n y",
                      "t r o p i c a l  p a r a d i s e",
                      "t r o u t  s t r e a m",
                      "t h e  w e s t  w i n g",
                      "t i n s e l t o w n",
                      "u p s c a l e  h o t e l",
                      "v i d e o  a r c a d e",
                      "v i c t o r i a n  h o m e",
                      "w e d d i n g  c h a p e l",
                      "w h i t e  s a n d  b e a c h",
                      "w o r l d ' s  l o n g e s t  s t r e e t",
                      "w r a p a r o u n d  p o r c h",
                      "w h i t e  h o u s e  l a w n",
                      "w i n e  c o u n t r y",
                      "a q u a t i c  g a r d e n s",
                      "a g e - o l d  c h u r c h e s",
                      "a r t  g a l l e r y",
                      "a n c i e n t  t e m p l e s",
                      "b o t a n i c a l  g a r d e n s",
                      "b a c k  a l l e y",
                      "b o u t i q u e",
                      "b r e a t h t a k i n g  c a n a d i a n  c i t y",
                      "b u s y  s t r e e t s",
                      "c o f f e e  s h o p s",
                      "c a p i t a l  c i t y  o f  f r a n c e",
                      "c h u r c h e s  a n d  s y n a g o g u e s",
                      "c o l l e g e s  & u n i v e r s i t i e s",
                      "c o a s t a l  m e a d o w s",
                      "c o r n e r  o f f i c e",
                      "c o v e r e d  p o r c h",
                      "d i v e r s e  r e s t a u r a n t s",
                      "f l a w l e s s  s a n d y  b e a c h e s",
                      "g r e a t  r e s t a u r a n t s",
                      "g o t h i c  c a t h e d r a l s",
                      "h u m i d  l o w l a n d  j u n g l e s",
                      "h i s t o r i c a l  s i t e s",
                      "i v y  l e a g u e  c o l l e g e s",
                      "m a r i n e  b a r r a c k s",
                      "m u s e u m  m i l e",
                      "n a r r o w  c o b b l e s t o n e  s t r e e t s",
                      "n e o c l a s s i c a l  b u i l d i n g s",
                      "n i g h t c l u b s",
                      "p l a y g r o u n d",
                      "r o w  h o u s e s",
                      "s t a t e  c a p i t a l s",
                      "s c h o o l  c a f e t e r i a",
                      "t a c o  s t a n d",
                      "t h e  a p p i a n  w a y",
                      "t h e  g u l f  c o a s t",
                      "t h e  s k y d e c k  a t  w i l l i s  t o w e r",
                      "t r i b a l  l a n d s",
                      "t r e n d y  s h o p s",
                      "w h i t e w a s h e d  h o t e l s",
                      "w o r l d - f a m o u s  p a r k s  & a t t r a c t i o n s",
                      "a i r  f o r c e  o n e",
                      "a m e r i c a n  s t o c k  e x c h a n g e",
                      "b a s k e t b a l l  s t a r  a l l e n  i v e r s o n",
                      "b e n  s t i l l e r",
                      "b e n  a f f l e c k",
                      "b u z z  a l d r i n",
                      "b o s t o n  b r u i n s",
                      "b i l l  o f  r i g h t s",
                      "b u g s y  s i e g e l",
                      "c a l g a r y  f l a m e s",
                      "c o m p o s e r  j o h a n n  s e b a s t i a n  b a c h",
                      "e l i  m a n n i n g",
                      "f r e d e r i c k  d o u g l a s s",
                      "j a m e s  e a r l  j o n e s",
                      "j e r e m y  s i s t o",
                      "j i m m y  f a l l o n",
                      "k e v i n  d i l l o n",
                      "l a r r y  b i r d",
                      "l a n c e  b u r t o n",
                      "m a r v e l  c o m i c s",
                      "m a r k  h a r m o n",
                      "m o n t y  p y t h o n",
                      "m e l  b r o o k s",
                      "m i c h e l l e  o b a m a",
                      "m o n a  l i s a",
                      "n e i l  p a t r i c k  h a r r i s",
                      "n e i l  s i m o n",
                      "p r i n c e  h a r r y",
                      "p u r d u e  u n i v e r s i t y",
                      "r y a n  p h i l l i p p e",
                      "s a n  f r a n c i s c o  g i a n t s",
                      "s i n g e r  t i m  m c g r a w",
                      "s u r v i v o r  h o s t  j e f f  p r o b s t",
                      "t h e  v e l v e t  u n d e r g r o u n d",
                      "t h e  b r a d f o r d  e x c h a n g e",
                      "t h e  r o l l i n g  s t o n e s",
                      "t h e  y a n k e e s",
                      "t i k i  b a r b e r",
                      "u .s . a i r  f o r c e  a c a d e m y",
                      "u .s . d e p a r t m e n t  o f  e d u c a t i o n",
                      "u n i t e d  s t a t e s  c o a s t  g u a r d",
                      "u t a h  j a z z",
                      "w a s h i n g t o n  n a t i o n a l s",
                      "w a s h i n g t o n  r e d s k i n s",
                      "a d a m  & e v e",
                      "b a s k e t b a l l  s t a r  l e b r o n  j a m e s",
                      "b o s t o n  r e d  s o x",
                      "b r a d l e y  c o o p e r",
                      "c i r q u e  d u  s o l e i l",
                      "d e n z e l  w a s h i n g t o n",
                      "n a t i o n a l  b a s k e t b a l l  l e a g u e",
                      "o r v i l l e  & w i l b u r  w r i g h t",
                      "u n i v e r s i t y  o f  n o t r e  d a m e",
                      "a  p o c k e t f u l  o f  r y e",
                      "a  p i c t u r e  i s  w o r t h  a  t h o u s a n d  w o r d s",
                      "c a l l  m e  i s h m a e l",
                      "g o o d  g r i e f  c h a r l i e  b r o w n",
                      "j a c k  b e  q u i c k",
                      "l i t t l e  b 0- p e e p  h a s  l o s t  h e r  s h e e p",
                      "l o n d o n  b r i d g e  i s  f a l l i n g  d o w n",
                      "a l l - s t a r  c a s t",
                      "c a m e r a s  r o l l i n g",
                      "d o c u m e n t a r y  f i l m",
                      "f i l m  r e v i e w",
                      "m a y  i  h a v e  a  d r u m r o l l  p l e a s e ?",
                      "m u s i c a l  c o m e d y",
                      "o p e n  a u d i t i o n",
                      "s e a s o n  f i n a l e",
                      "s i n g i n g  s e n s a t i o n",
                      "s t a g e  a c t o r s",
                      "i  d i d  i t  m y  w a y",
                      "o n e  f o r  t h e  m o n e y  t w o  f o r  t h e  s h o w",
                      "d e d i c a t e d  t o  t h e  o n e  i  l o v e",
                      "a  f r i e n d l y  r e m i n d e r",
                      "a  p l e a s a n t  s u r p r i s e",
                      "a  b r i s k  p a c e",
                      "a  s h a r p  p e n c i l",
                      "a c h e s  & p a i n s",
                      "a m e r i c a n  f l a g",
                      "a r c h e r y",
                      "a l p i n e  g l a c i e r s",
                      "a s s e m b l y  l i n e",
                      "a i r c r a f t  c a r r i e r",
                      "a n  a m a z i n g  v i e w  o f  t h e  s k y l i n e",
                      "b r i g h t  b l u e  s k y",
                      "b a t t l e s h i p",
                      "b a t t i n g  h e l m e t",
                      "b i r t h d a y  p r e s e n t",
                      "b i g  d e c i s i o n",
                      "b l u e  r i b b o n",
                      "b o o k m a r k",
                      "c o r n c o b  p i p e",
                      "c a l y p s o  m u s i c",
                      "c h a i n s a w",
                      "c o l o r  p r i n t e r",
                      "c l a s s i c a l  m u s i c",
                      "c o m p u t e r  s o f t w a r e",
                      "d a z z l i n g  n i g h t l i f e",
                      "d e s i g n e r  l u g g a g e",
                      "d o t t e d  l i n e",
                      "d o u b l e  c o u p o n s",
                      "e n g r a v e d  i n v i t a t i o n s",
                      "e y e l a s h  c u r l e r",
                      "e n g a g i n g  c o n v e r s a t i o n",
                      "e y e b r o w  p e n c i l",
                      "f i g h t e r  j e t",
                      "f l o o d l i g h t",
                      "f a v o r a b l e  c l i m a t e",
                      "f i n e  d i n i n g",
                      "f l e e t i n g  m o m e n t",
                      "f o n d  m e m o r i e s",
                      "f r e i g h t  e l e v a t o r",
                      "f u n  h o b b y",
                      "g o o d  p u b l i c i t y",
                      "g u i l t y  p l e a s u r e",
                      "g o o d  j u d g m e n t",
                      "g o o d  l u c k  c h a r m",
                      "g r e a t  p e r s o n a l i t y",
                      "h a r d b a c k  b o o k",
                      "h e a l i n g  m a s s a g e",
                      "h d  d i g i t a l  c a m e r a",
                      "h o o d e d  s w e a t s h i r t",
                      "h u m b l e  h o n o r",
                      "i c y  s n o w b a n k",
                      "j e a n  j a c k e t",
                      "j u n i o r  c o l l e g e  f o o t b a l l",
                      "j u m b o  s n o w f l a k e s",
                      "l e a d i n g  n a t i o n a l  b r a n d s",
                      "l e i s u r e  s u i t",
                      "l i g h t i n g  d i s p l a y s",
                      "l i n e n  h a n d k e r c h i e f",
                      "l i f e  s a v i n g s",
                      "l o f t  b e d",
                      "l u n c h  m o n e y",
                      "l i f e t i m e  w a r r a n t y",
                      "m i l d  w e a t h e r",
                      "m a g a z i n e  a r t i c l e",
                      "m e m b e r s h i p  d u e s",
                      "m i n i m u m  w a g e",
                      "m o d e r n  a r t",
                      "m u d  f l a p s",
                      "m a t h  q u i z",
                      "m o n u m e n t s",
                      "n a t u r a l  a b i l i t y",
                      "n a t u r a l  h a b i t a t",
                      "n a v a l  f l e e t",
                      "o v e r n i g h t  d e l i v e r y",
                      "p e r f e c t  r e p o r t  c a r d",
                      "p i r a t e  b o o t y",
                      "p a d l o c k",
                      "p i l o t s  l i c e n s e",
                      "p l e a s a n t  c o n v e r s a t i o n",
                      "p r e t t y  s m i l e s",
                      "p r e s i d e n t i a l  s e a l",
                      "q u i c k  r u n d o w n",
                      "r a d i o  s t a t i o n",
                      "r a d i o  t u n e r",
                      "r e s o r t  v a c a t i o n",
                      "s a d d l e b a g",
                      "s a v i n g s  a c c o u n t",
                      "s c a f f o l d",
                      "s e n a t o r i a l  g a v e l",
                      "s p a r e  k e y",
                      "s p a r k l i n g  s k y l i n e",
                      "s p e c t a c u l a r  s u n s e t",
                      "s u n n y  f o r e c a s t",
                      "s t a r t i n g  r e v e l a t i o n",
                      "s u b s t a n t i v e  a r g u m e n t",
                      "s u b w a y  s y s t e m",
                      "t e m p t i n g  o f f e r",
                      "t r e e  t r u n k",
                      "t h e  c o n s t i t u t i o n",
                      "t h e  s o o t h i n g  s o u n d  o f  t h e  w a v e s",
                      "t i k i  s t a t u e",
                      "t h u n d e r o u s  r o u n d  o f  a p p l a u s e",
                      "t o l l - f r e e  c u s t o m e r  s e r v i c e  n u m b e r",
                      "t o t e m  p o l e",
                      "t r e n d y  h a i r s t y l e",
                      "u n i q u e  u r b a n  e x p e r i e n c e",
                      "u n i q u e  b u i l d i n g s",
                      "u p  t e m p o",
                      "v a c a t i o n  o f  m y  d r e a m s",
                      "w i n n i n g  t i c k e t",
                      "w i n n i n g  s t r e a k",
                      "w r a p p e d  p r e s e n t s",
                      "w a r m  a n d  s u n n y  c l i m a t e",
                      "w a r m  w e a t h e r",
                      "w a t e r  s l i d e",
                      "w i t c h ' s  p o t i o n",
                      "w o o d e n  t o y  b o x",
                      "w o o d e n  u k u l e l e",
                      "a c t i o n  f i g u r e s",
                      "a c r e s  o f  l a n d",
                      "a d v e r s e  c o n d i t i o n s",
                      "a l k a l i n e  b a t t e r i e s",
                      "a m a z i n g  h i k e s",
                      "a r c h i t e c t u r a l  t r e a s u r e s",
                      "b l u e  s k i e s",
                      "b u s i n e s s  h o u r s",
                      "c a r t i l a g e  & v e r t e b r a e",
                      "c o l o r f u l  e m b r o i d e r e d  b l o u s e s",
                      "d i v e r s e  c u l t u r e s",
                      "e m e r g e n c y  s u p p l i e s",
                      "e n g r a v e d  i n v i t a t i o n s",
                      "f o n d  m e m o r i e s",
                      "f u n k y  g a d g e t s",
                      "f i n g e r p r i n t s",
                      "h o l i d a y  o r n a m e n t s",
                      "h o t  h u m i d  s u m m e r s",
                      "l u c k y  n u m b e r s",
                      "m a j o r  i s s u e s",
                      "m a s k i n g  t a p e",
                      "m e o w s  & w o o f s",
                      "m e t a l  s c u l p t u r e s",
                      "m o n u m e n t s",
                      "o n - c a m p u s  a c t i v i t i e s",
                      "o u t d o o r  a c t i v i t i e s",
                      "r o s y  c h e e k s",
                      "s h o r t  s t o r i e s",
                      "s o l a r  p a n e l s",
                      "s t r i k i n g  s i m i l a r i t i e s",
                      "s k y s c r a p e r s",
                      "s t r e n g t h s  a n d  w e a k n e s s e s",
                      "s t o n y  c o r a l  r e e f s",
                      "s u m m e r  w a r d r o b e",
                      "s t r i c t  g u i d e l i n e s",
                      "s u n - k i s s e d  c h e e k s",
                      "t i c k e t s  t o  a  r o c k  c o n c e r t",
                      "t a b l e  m a n n e r s",
                      "t i c k e t s  t o  a  m i a m i  h e a t  g a m e",
                      "u n i q u e  b u i l d i n g s",
                      "u n i q u e  i s l a n d s",
                      "w a r m  s u n s h i n e",
                      "w a t e r f a l l s",
                      "a  c h r i s t m a s  c a r o l",
                      "a l i c e ' s  a d v e n t u r e s  i n  w o n d e r l a n d",
                      "a l l  t h a t  j a z z",
                      "d e t r o i t  f r e e  p r e s s",
                      "g o o d  h o u s e k e e p i n g",
                      "g q  m a g a z i n e",
                      "i  k n o w  w h y  t h e  c a g e d  b i r d  s i n g s",
                      "j e r s e y  b o y s",
                      "r o l l i n g  s t o n e  m a g a z i n e",
                      "t h e  a r i z o n a  r e p u b l i c",
                      "t h e  w a s h i n g t o n  p o s t",
                      "t h e  w o r l d  a l m a n a c  f o r  k i d s",
                      "t h e  t h r e e  l i t t l e  p i g s",
                      "f a m i l y  g u y",
                      "h o w  i  m e t  y o u r  m o t h e r",
                      "m e n  o f  a  c e r t a i n  a g e",
                      "s o  y o u  t h i n k  y o u  c a n  d a n c e",
                      "t h e  c l e v e l a n d  s h o w",
                      "t h e  r e a l  h o u s e w i v e s  o f  n e w  y o r k  c i t y",
                      "a t t e n d i n g  w i m b l e d o n",
                      "b u y i n g  a  n e w  c o a t",
                      "b u y i n g  t a c o s  f r o m  a  s t r e e t  v e n d o r",
                      "c o o k i n g  f r e s h l y  c a u g h t  f i s h",
                      "c o l l e c t i n g  s e a s h e l l s",
                      "d a n c i n g  i n  t h e  s a n d",
                      "d i g g i n g  m y  t o e s  i n  t h e  s a n d",
                      "d i s c o v e r i n g  c a n a d i a n  a r t",
                      "d u s t i n g  m y  d e s k",
                      "e a t i n g  r a w  v e g e t a b l e s",
                      "e n j o y i n g  a  r o m a n t i c  v i e w  o f  t h e  c i t y",
                      "e n j o y i n g  t h e  v i e w  f r o m  n o b  h i l l",
                      "f e e d i n g  t h e  d u c k s  a t  t h e  p u b l i c  g a r d e n",
                      "f l y i n g  t o  a  f o r e i g n  c o u n t r y",
                      "g o i n g  t o  t h e  b a l l e t",
                      "g a r g l i n g  w i t h  m o u t h w a s h",
                      "g e t t i n g  g o o s e b u m p s",
                      "g o i n g  f o r  a  b i k e  r i d e",
                      "g o i n g  t o  t h e  g y m",
                      "g o i n g  t o  a  n i g h t c l u b",
                      "h a i l i n g  a  c a b",
                      "k a y a k i n g  i n  t h e  b a y",
                      "l e a r n i n g  t o  h u l a",
                      "l i s t e n i n g  t o  t h e  c h i m e s  o f  b i g  b e n",
                      "p a i n t i n g  a  p i c t u r e",
                      "p a i n t i n g  t h e  h o u s e",
                      "p a n n i n g  f o r  g o l d",
                      "r e l a x i n g  p o o l s i d e",
                      "r e m o d e l i n g  t h e  k i t c h e n",
                      "s e n d i n g  t h a n k  y o u  n o t e s",
                      "s h o p p i n g  i n  s o h o",
                      "s n o r k e l i n g  i n  c l e a r  b l u e  w a t e r",
                      "s t a y i n g  i n  a  b e a c h  b u n g a l o w",
                      "s c r u b b i n g  t h e  f l o o r",
                      "s p e a k i n g  f r e n c h  a n d  e n g l i s h",
                      "s t a n d i n g  i n  m y  b a r e  f e e t",
                      "s h a k i n g  h a n d s  w i t h  m i n n i e  m o u s e",
                      "s h o p p i n g  a t  t h e  a n t i q u e  f a i r",
                      "s p e n d i n g  t h e  d a y  h i k i n g  i n  t h e  m o u n t a i n s",
                      "s e e i n g  a  m o v i e",
                      "s h i n i n g  m y  s h o e s",
                      "s t a n d i n g  i n  l i n e",
                      "s u n n i n g  m y s e l f  o n  t h e  b e a c h",
                      "t a k i n g  i n  a n  a f t e r n o o n  m o v i e",
                      "t a k i n g  a  d a y  t r i p  t o  k i s s i m m e e",
                      "t a k i n g  i t  e a s y",
                      "t a k i n g  a  d a y  t r i p  t o  t h e  b e a c h",
                      "t e l l i n g  t a l l  t a l e s",
                      "t o u r i n g  t h e  i s l a n d  o n  h o r s e b a c k",
                      "t r a v e l i n g  i n  a  s n o w m o b i l e",
                      "v i s i t i n g  t h e  z o o",
                      "v i s i t i n g  t h e  o l d  r o y a l  p a l a c e",
                      "w a t c h i n g  t h e  h o c k e y  g a m e",
                      "w i p i n g  o f f  m y  s h o e s",
                      "z o o m i n g  d o w n  a  w a t e r  s l i d e"};